SELECT * FROM salespeople; 

SELECT DISTINCT SNUM FROM orders;

SELECT SNAME,COMM FROM salespeople WHERE UPPER(CITY) LIKE 'LONDON';

SELECT * FROM Customer WHERE RATING=100; 

SELECT ONUM, AMOUNT, ODATE FROM Orders; 

SELECT * FROM Customer WHERE UPPER(CITY) LIKE 'SAN JOSE' AND RATING > 200; 

SELECT * FROM Customer WHERE UPPER(CITY) LIKE 'SAN JOSE' OR RATING > 200; 

SELECT * FROM Orders WHERE AMOUNT > 1000;

SELECT SNAME,UPPER(CITY) FROM salespeople WHERE COMM > 0.10;

SELECT * FROM Customer WHERE RATING > 100 OR UPPER(CITY) LIKE 'Rome'; 

SELECT SNAME,COMM FROM salespeople WHERE UPPER(UPPER(CITY)) LIKE 'LONDON' OR UPPER(UPPER(CITY)) LIKE 'BARCELONA';

SELECT SNAME,UPPER(CITY) FROM salespeople WHERE COMM > 0.10 AND COMM < 0.12;

SELECT * FROM Customer WHERE CITY IS NULL; 

SELECT * FROM Orders WHERE ODATE = '3-oct-16' AND ODATE = '3-oct-16'; 

SELECT * FROM Customer, salespeople WHERE salespeople.SNUM = Customer.SNUM AND salespeople.SNAME UPPER(SNAME) IN ('PEEL', 'MOTIKA');  

SELECT * FROM Customer WHERE CNAME = 'A%' OR CNAME = 'B%'; 

SELECT * FROM Orders WHERE AMOUNT IS NOT NULL OR AMOUNT = 0; 

SELECT COUNT(CNUM) FROM orders; 

SELECT MAX(AMOUNT), SNUM FROM orders GROUP BY(SNUM) ORDER BY ; 

/* 40 */

SELECT  DISTINCT (SNAME,CNAME)  FROM Customer, salespeople, orders WHERE salespeople.SNUM = orders.SNUM and Customer.CNUM = orders.CNUM ORDER BY salespeople.SNUM; 
/*41*/
SELECT SNAME, CITY FROM salespeople s WHERE s.CITY = (SELECT CITY FROM salespeople s1 WHERE s1.CITY = s.CITY AND s.SNUM != s1.SNUM);  
/*42 */ 
SELECT DISTINCT CNAME, ONUM FROM Customer, orders WHERE Customer.CNUM = orders.CNUM ORDER BY (Orders.ONUM); 
/* 43 */ 
SELECT CNAME, RATING FROM Customer WHERE RATING = (SELECT RATING FROM Customer WHERE CNAME LIKE 'Hoffman'); 
/* 44 */ 
SELECT SNAME, ONUM, AMOUNT FROM salespeople, orders WHERE salespeople.SNUM = orders.SNUM AND salespeople.SNAME LIKE 'Motika'; 
/* 45 */ 
SELECT SNAME, ONUM, AMOUNT FROM Customer,salespeople, orders WHERE salespeople.SNUM = orders.SNUM AND orders.CNUM = Customer.CNUM AND CNAME LIKE 'Hoffman'; 

/* 48 */
SELECT ONUM, AMOUNT, O.SNUM FROM ORDERS O, SALESPEOPLE S WHERE O.SNUM = S.SNUM AND UPPER(CITY)='LONDON'; 
/* 51 */
SELECT COUNT(CNAME) FROM Customer C WHERE C.RATING > (SELECT AVG(RATING) FROM CUSTOMER WHERE UPPER(CITY) LIKE 'SAN JOSE'); 

/* 52 */
SELECT C.CNAME,O.ONUM, O.AMOUNT FROM Customer C, Orders O WHERE O.CNUM = C.CNUM AND C.CNUM = (SELECT CNUM FROM Customer WHERE UPPER(CNAME)='GRASS');


/* 53 */
SELECT CNAME, RATING, AMOUNT AS ORDER_AMOUNT FROM CUSTOMER C, ORDERS O WHERE O.CNUM = C.CNUM AND O.AMOUNT > (SELECT AVG(AMOUNT) FROM ORDERS); 

/* 55 */
SELECT C.CNAME, O.ONUM,O.ODATE,O.AMOUNT FROM ORDERS O, CUSTOMER C WHERE C.CNUM = O.CNUM AND ODATE=TO_DATE('03-10-2016','dd-mm-yyyy');
