SELECT * FROM salespeople; 

SELECT DISTINCT SNUM FROM orders;

SELECT SNAME,COMM FROM salespeople WHERE CITY LIKE 'LONDON';

SELECT * FROM Customers WHERE RATING=100; 

SELECT ONUM, AMOUNT, ODATE FROM Orders; 

SELECT * FROM Customers WHERE CITY LIKE 'San Jose' AND RATING > 200; 

SELECT * FROM Customers WHERE CITY LIKE 'San Jose' OR RATING > 200; 

SELECT * FROM Orders WHERE AMOUNT > 1000;

SELECT SNAME,CITY FROM salespeople WHERE COMM > 0.10;






